### ISSUE TITLE
Camera function

### ISSUE THREAD

**Issue by SensRy** [HighTemplar-wjiang/pyqt5_opencv#1]
Hi!
When I click a camera button I got:
Error: Exception while reading next frame
'NoneType' object has no attribute 'copy'

**Comment by HighTemplar-wjiang** [comment]
That means reading from webcam failed.

Can you tell me your OS and OpenCV lib version? I also had some trouble when streaming webcam in Ubuntu 16.04 with python3, while python2 works fine.

Probably it's the OpenCV's library issue, please refer to this thread:
https://github.com/opencv/opencv/issues/8471

**Comment by SensRy** [comment]
Windows 10, python 3, OpenCV 3.3.0

**Comment by HighTemplar-wjiang** [comment]
It seems that OpenCV cannot read the FPS of the webcam, but it shouldn't cause this issue. I have modified the source code anyway, can you update and try again? It works in my Windows 10 PC.

There is an easy way to test your environment, you may try the OpenCV official python samples:
https://github.com/opencv/opencv/tree/master/samples/python

Try "python camshift.py", if it works, then your OpenCV configuration should be fine.

**Comment by SensRy** [comment]
Great. Everything is working!
